# Generated by Django 3.1.3 on 2020-11-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconsumption',
            options={'verbose_name': 'User Consumption'},
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='datestamp',
            field=models.DateTimeField(),
        ),
    ]
