# Generated by Django 3.1.3 on 2020-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201126_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsumption',
            name='gram',
            field=models.IntegerField(default=1),
        ),
    ]
