# Generated by Django 3.1.3 on 2020-11-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userconsumption_gram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconsumption',
            old_name='gram',
            new_name='grams',
        ),
    ]
