# Generated by Django 3.1.3 on 2020-11-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userconsumption_fiber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconsumption',
            options={},
        ),
    ]
