# Generated by Django 3.1.3 on 2020-11-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userconsumption_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsumption',
            name='datestamp',
            field=models.DateField(),
        ),
    ]
