# Generated by Django 3.1.3 on 2020-11-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201126_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconsumption',
            name='datestamp',
        ),
    ]
