# Generated by Django 3.1.3 on 2020-11-27 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userconsumption_datestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsumption',
            name='datestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
