# Generated by Django 3.1.3 on 2020-11-27 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userconsumption_datestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsumption',
            name='carbohydrates',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='datestamp',
            field=models.DateTimeField(default=datetime.date(2020, 11, 27)),
        ),
    ]
