# Generated by Django 3.1.3 on 2020-11-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201127_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsumption',
            name='carbohydrates',
            field=models.IntegerField(default=1),
        ),
    ]
