# Generated by Django 3.1.3 on 2020-11-27 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201127_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsumption',
            name='datestamp',
            field=models.DateField(default=datetime.datetime),
        ),
    ]
