# Generated by Django 3.1.3 on 2020-11-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201129_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsumption',
            name='calories',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='carbohydrates',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='fat',
            field=models.IntegerField(default=None),
        ),
    ]
