# Generated by Django 3.1.3 on 2020-11-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20201129_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.IntegerField(default=None)),
            ],
        ),
    ]
