# Generated by Django 3.1.3 on 2020-11-30 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_caloriegoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsumption',
            name='datestamp',
            field=models.DateField(default=datetime.date(2020, 11, 30)),
        ),
    ]
