# Generated by Django 3.1.3 on 2020-11-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20201130_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsumption',
            name='calories',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='carbohydrates',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='fat',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='protein',
            field=models.IntegerField(default=None),
        ),
    ]
