# Generated by Django 3.1.3 on 2020-12-01 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20201130_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsumption',
            name='datestamp',
            field=models.DateField(default=datetime.date(2020, 12, 1)),
        ),
    ]
