# Generated by Django 3.1.3 on 2020-12-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_caloriegoal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsumption',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
