# Generated by Django 3.1.3 on 2020-12-02 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_auto_20201202_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_fat', models.IntegerField(default=None)),
                ('daily_protein', models.IntegerField(default=None)),
                ('daily_carbohydrates', models.IntegerField(default=None)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
