# Generated by Django 3.1.3 on 2020-12-04 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_macrogoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrogoal',
            name='daily_carbohydrates',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='macrogoal',
            name='daily_fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='macrogoal',
            name='daily_protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='carbohydrates',
            field=models.IntegerField(default=datetime.date(2020, 12, 4)),
        ),
    ]
